# .trivyignore.yaml

misconfigurations:

    #SECURITY GROUP -------------------------------------------------------------
  - id: AVD-AWS-0104 #(CRITICAL): Security group rule allows unrestricted egress to any IP address.
    statement: "Ignore this for testing purposes."
    
  - id: AVD-AWS-0107 #(HIGH): Security group rule allows unrestricted ingress from any IP address.
    statement: "Ignore this for testing purposes."

    #SUBNET ----------------------------------------------------------------------
  - id: AVD-AWS-0164 #(HIGH): Subnet associates public IP address.
    statement: "Ignore this for testing purposes."

    #VPC -------------------------------------------------------------------------
  - id: AVD-AWS-0178 #(MEDIUM): VPC does not have VPC Flow Logs enabled. 
    statement: "Will implement once Module for IAM is created."
